### ISSUE TITLE
How to implement support for Socket.IO in .NET client

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/consumer_api_client#34]
## Description

While the JavaScript side of things has several fully functional Socket.IO implementations for various scenarios, the .NET community has not.

This issue should contain the discussion towards choosing a .NET Library that we can use to connect to our Socket.IO server on the backend.

### Background Info

Socket.IO uses WebSocket as a transport when possible. On top of the physical transport layer there is the Socket.IO Protocol.

Further info [here](https://socket.io/docs/internals/) and [here](https://github.com/socketio/socket.io-protocol).

That means - _if needed_ - we can use any general purpose WebSocket implementation, as long as we adhere to the Socket.IO Protocol.

## Possible solution

The following libraries have already been evaluated to some degree:

---

##### https://github.com/Quobject/SocketIoClientDotNet
This library is no longer maintained.

Also there is no fully functional support of all the features Socket.IO has.
It misses:
* Custom Headers in Handshake (we need `Authorization`)
* Namespace-Support and Multiplexing don't seem to be fully supported

---
##### https://github.com/IBM/socket-io
* Only supports rooms (no namespaces)
* Very fresh - likely unstable

---
##### https://github.com/sta/websocket-sharp/
* Seems very mature
* Does not implement Socket.IO protocol
* Does not support custom headers in handshake (we need `Authorization`) - see [here](https://github.com/sta/websocket-sharp/pull/22) for insights why the maintainer is strictly against it

---
##### https://github.com/felixhao28/websocket-sharp
* Fork from above, but with support for custom headers

---

Right now the easiest and most stable way seems to be to use the forked library without Socket.IO protocol implementation.

The only custom thing about this we would need to implement seems to be connecting to the namespace.

I'm not sure yet if the connection upgrade will be seamless, but afaik it is not specific to Socket.IO.

A first implementation with the proposed solution can be found here: https://github.com/process-engine/consumer_api_client/tree/feature/socket_io_dotnet

**Comment by ElRaptorus** [comment]
Das wird ein Thema für die AtlasEngine.
